### ISSUE TITLE
SchemaRegistryCluster creation fails with "Cannot find region" – likely due to deprecated region field

### ISSUE THREAD

**Issue by davidsantiagom** [crossplane-contrib/provider-confluent#33]
### What happened?

When attempting to create a `SchemaRegistryCluster` resource, the resource fails with the following error:

`apply failed: error creating Schema Registry Cluster "": 400 Bad Request: resource not found: Cannot find region:`

This appears to be caused by the `spec.forProvider.region.id` field. I have tried all reasonable values including `eu-west-1`, `EU_WEST_1`, `AWS_EU_WEST_1`, `EU`, and `eu-west1`,...but all result in the same error.

After some research, I discovered that the region field may now be deprecated in the Confluent Cloud API. According to [terraform-provider-confluent issue #373](https://github.com/confluentinc/terraform-provider-confluent/issues/373), the region is no longer explicitly set and is instead inferred from the associated Kafka cluster.

This suggests the Crossplane provider may be using an outdated API schema that is no longer compatible with the current Confluent Cloud behavior.

### How can we reproduce it?
Use the following resource definition in a composition:

```
apiVersion: confluent.crossplane.io/v1alpha1
kind: SchemaRegistryCluster
metadata:
  name: schema-registry
spec:
  forProvider:
    environment:
      - id: <env-id>
    package: ESSENTIALS
    region:
      - id: <region-id>  # All tested values fail similarly
  providerConfigRef:
    name: confluent-provider
```
**Expected:** Schema Registry cluster is created successfully.
**Actual:** Fails with `400 Bad Request – resource not found: Cannot find region`.

**Note:** removing the region field results in a validation error, so it is currently required by the CRD.

### What environment did it happen in?

- Crossplane version: v1.19.0
- Crossplane provider-confluent version: v0.6.1
- Kubernetes distribution: Minikube
- Kubernetes version: v1.32
- Host machine: MacBook Pro M3 (Apple Silicon)
