### ISSUE TITLE
auth secret format

### ISSUE THREAD

**Issue by callum-stakater** [crossplane-contrib/provider-confluent#9]
Any hints on how the credentials need to be structured to make this provider work?

I found this https://github.com/crossplane-contrib/provider-confluent/blob/main/cluster/test/setup.sh#L6 but its a bit of a guessing game what is contained in : "${UPTEST_CLOUD_CREDENTIALS}"

**Comment by callum-stakater** [comment]
worked it out:

` ``kubectl -n crossplane create secret generic provider-confluent-secret --from-literal=credentials='{"cloud_api_key":"$API-KEY", "cloud_api_secret":"$API_SECRET"}' --dry-run=client -o yaml ```

**Comment by jtucci** [comment]
> worked it out:
> 
> `kubectl -n crossplane create secret generic provider-confluent-secret --from-literal=credentials='{"cloud_api_key":"$API_KEY", "cloud_api_secret":"$API_SECRET"}' --dry-run=client -o yaml`

Yup you got it! :)

**Comment by jtucci** [comment]
```yaml
kind: Secret
metadata:
  name: confluent-provider-config
  namespace: crossplane-system
data:
  credentials: '{"cloud_api_key":"$API_KEY", "cloud_api_secret":"$API_SECRET"}'
```
